# 项目相关配置
zshy:
    # 名称
    name: simple-qingting
    # 版本
    version: 4.6.2
    # 版权年份
    copyrightYear: 2021
    # 实例演示开关
    demoEnabled: false
    # 文件路径
    resource: /home/xshell/download
    # 获取ip地址开关
    addressEnabled: false
# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://rm-2ze26x1o96byuiowcvo.mysql.rds.aliyuncs.com:3306/simpleqingting?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
                username: simpleqingtingdb
                password: 1qaz2wsx
            # 从库数据源
            slave:
                url: jdbc:mysql://rm-2ze26x1o96byuiowcvo.mysql.rds.aliyuncs.com:3306/simpleqingting?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
                username: simpleqingtingdb
                password: 1qaz2wsx
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: exam
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

    redis:
        #单机机模式
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        lettuce:
            pool:
                #连接池最大链接数默认值为8
                max-active: 1000
                #连接池最大阻塞时间（使用负值表示没有限制）默认为-1
                max-wait: -1
                #连接池中的最大空闲连接数 默认为8
                max-idle: 8
                #连接池中的最小空闲连接数 默认为8
                min-idle: 1
        timeout: 3000